name : polaris-arctic-v0

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pyyaml
  - wget
  - tqdm
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - cartopy
  - gdal
  - gdown
  - netCDF4
  - cdsapi
  - rasterio

